<?php
/**
 * @file
 * Code for the Docent Schedules feature.
 */

include_once 'docent_schedules.features.inc';

function docent_schedules_views_pre_build(&$view) {
    dpm($view->display);
    if ($view->name == 'docent_tours') {
        global $user;
        $view->display['page_2']->handler->handlers['filter']['field_assigned_docent_target_id']->value['value'] = $user->uid;
        $view->display['panel_pane_2']->handler->handlers['filter']['field_assigned_docent_target_id']->value['value'] = $user->uid;
    }
}
